## my global config
global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "vector-vmagent"
    static_configs:
      - targets: [ "localhost:8429" ]
  - job_name: "vector"
    static_configs:
      - targets: [ "read:3100" ]
